# This is a basic workflow to help you get started with Actions

name: Builder CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      BASEROM_URL:
        description: Base ROM URL
        required: true
        default: https://master.dl.sourceforge.net/project/miui-ita/14/miui.it_EasyROM_LIME_V14.0.3.0.SJQMIXM_12.0.zip?viasf=1
      PORTROM_URL:
        description: Port ROM URL
        required: true
        default: https://bigota.d.miui.com/OS1.0.7.0.UMGEUXM/miui_TOPAZEEAGlobal_OS1.0.7.0.UMGEUXM_5b32c81f19_14.0.zip
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone scripts
        run: git clone https://github.com/toraidl/hyperos_port.git ./workspace

      # Runs a single command using the runners shell
      - name: Start porting
        run: |
          cd workspace
          sudo ./setup.sh
          sudo ./port.sh ${{ inputs.BASEROM_URL }} ${{ inputs.PORTROM_URL }}

      # Runs a set of commands using the runners shell
      - name: Upload
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          files: |
            workspace/out/*
          name: ${{ inputs.DEVICE_NAME }} (TWRP)
          tag_name: ${{ github.run_id }}
          body: |
            Manifest: ${{ inputs.MANIFEST_BRANCH }}
            Target: ${{ inputs.BUILD_TARGET }}.img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
